# Generated by Django 4.2.3 on 2023-07-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(default=1, max_length=150, verbose_name='создано'),
            preserve_default=False,
        ),
    ]
