# Generated by Django 4.2.3 on 2023-07-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(default=1, max_length=150, verbose_name='дополнение'),
            preserve_default=False,
        ),
    ]
